package unload.portia;

import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPostInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.registry.GameRegistry;
import net.minecraft.block.Block;
import net.minecraft.block.material.Material;
import net.minecraft.creativetab.CreativeTabs;
import net.minecraft.init.Blocks;
import net.minecraft.init.Items;
import net.minecraft.item.Item;
import net.minecraft.item.ItemArmor;
import net.minecraft.item.ItemDoor;
import net.minecraft.item.ItemStack;
import net.minecraftforge.common.util.EnumHelper;
import unload.portia.access.*;
import unload.portia.armor.*;
import unload.portia.specialblocks.*;

@Mod(modid = "portia", name = "Portia", version = "0.3.2")
public class Main {

	public static Block oldCloth;
    public static Block barrier;
    public static Block newConcrete;
    public static Block glazedTerracotta;
    public static Block coloredWood;
    public static Block coloredStone;
    public static Block coloredCobble;
    public static Block goldenDoor;
    public static Block diamondDoor;
    public static Block emeraldDoor;
    public static Block nullTexture;

    public static final Item.ToolMaterial emeraldItems = EnumHelper.addToolMaterial("emerald_items", 3, 950, 2.8F, 2.5F, 15);
    public static final ItemArmor.ArmorMaterial emeraldArmor = EnumHelper.addArmorMaterial("emerald_armor", 29, new int[]{3,7,5,3}, 18);
    public static final Item.ToolMaterial redstoneItems = EnumHelper.addToolMaterial("redstone_items", 2, 680, 1.9F, 1.5F, 21);
    public static final ItemArmor.ArmorMaterial redstoneArmor = EnumHelper.addArmorMaterial("redstone_armor", 25, new int[]{2,6,3,2}, 23);
    public static final Item.ToolMaterial lapisItems = EnumHelper.addToolMaterial("lapis_items", 2, 500, 1.6F, 1F, 38);
    public static final ItemArmor.ArmorMaterial lapisArmor = EnumHelper.addArmorMaterial("lapis_armor", 21, new int[]{2,5,3,2}, 40);
    public static Item chain;
    public static Item diamondChain;
    public static Item ironNugget;
    public static Item diamondNugget;
    public static Item emeraldPickaxe;
    public static Item emeraldAxe;
    public static Item emeraldShovel;
    public static Item emeraldHoe;
    public static Item emeraldSword;
    public static Item emeraldHelmet;
    public static Item emeraldChestplate;
    public static Item emeraldLeggings;
    public static Item emeraldBoots;
    public static Item redstonePickaxe;
    public static Item redstoneAxe;
    public static Item redstoneShovel;
    public static Item redstoneHoe;
    public static Item redstoneSword;
    public static Item redstoneHelmet;
    public static Item redstoneChestplate;
    public static Item redstoneLeggings;
    public static Item redstoneBoots;
    public static Item lapisPickaxe;
    public static Item lapisAxe;
    public static Item lapisShovel;
    public static Item lapisHoe;
    public static Item lapisSword;
    public static Item lapisHelmet;
    public static Item lapisChestplate;
    public static Item lapisLeggings;
    public static Item lapisBoots;

    public static Item goldenDoorI;
    public static Item diamondDoorI;
    public static Item emeraldDoorI;
    @EventHandler
    public void preInit(FMLPreInitializationEvent event) {
		oldCloth = new BlockClassicCloth(Material.cloth).setBlockName("cloth").setStepSound(Block.soundTypeCloth).setHardness(0.8F).setBlockTextureName("portia:cloth").setCreativeTab(portiaBlocks);
        GameRegistry.registerBlock(oldCloth, MetadataItemBlocks.class, "cloth");
        barrier = new BlockBorder(Material.rock).setBlockName("barrier").setBlockTextureName("portia:barrier").setHardness(-1.0F).setResistance(3600000F).setCreativeTab(portiaBlocks);
        GameRegistry.registerBlock(barrier, "barrier");
        newConcrete = new BlockColored(Material.rock).setBlockName("concrete").setHardness(1.8F).setResistance(1.8F).setBlockTextureName("portia:concrete").setCreativeTab(portiaBlocks);
        GameRegistry.registerBlock(newConcrete, MetadataItemBlocks.class, "concrete");
        glazedTerracotta = new BlockColored(Material.rock).setBlockName("glazedTerracotta").setBlockTextureName("portia:glazed_terracotta").setCreativeTab(portiaBlocks);
        GameRegistry.registerBlock(glazedTerracotta, MetadataItemBlocks.class, "glazed_stained_clay");
        coloredWood = new BlockColored(Material.wood).setBlockName("woodColored").setStepSound(Block.soundTypeWood).setHardness(2.0F).setResistance(5.0F).setBlockTextureName("portia:woodcolored").setCreativeTab(portiaBlocks);
        GameRegistry.registerBlock(coloredWood, MetadataItemBlocks.class, "colored_wood");
        coloredStone = new BlockColored(Material.rock).setBlockName("stoneColored").setHardness(1.5F).setResistance(10F).setBlockTextureName("portia:stonecolored").setCreativeTab(portiaBlocks);
        GameRegistry.registerBlock(coloredStone, MetadataItemBlocks.class, "colored_stone");
        coloredCobble = new BlockColored(Material.rock).setBlockName("cobbleColored").setBlockTextureName("portia:cobblecolored").setCreativeTab(portiaBlocks);
        GameRegistry.registerBlock(coloredCobble, MetadataItemBlocks.class, "colored_cobblestone");
        goldenDoor = new BlockGoldenDoor(Material.iron).setHardness(4.0F).setStepSound(Block.soundTypeMetal).setBlockName("doorGolden").setBlockTextureName("portia:golden_door");
        GameRegistry.registerBlock(goldenDoor, "golden_door");
        diamondDoor = new BlockDiamondDoor(Material.iron).setHardness(10F).setStepSound(Block.soundTypeMetal).setBlockName("doorDiamond").setBlockTextureName("portia:diamond_door");
        GameRegistry.registerBlock(diamondDoor, "diamond_door");
        emeraldDoor = new BlockEmeraldDoor(Material.iron).setHardness(7.5F).setStepSound(Block.soundTypeMetal).setBlockName("doorEmerald").setBlockTextureName("portia:emerald_door");
        GameRegistry.registerBlock(emeraldDoor, "emerald_door");
        nullTexture = new BlockNormal(Material.rock);
        GameRegistry.registerBlock(nullTexture, "nulltex");
        chain = new Item().setUnlocalizedName("chain").setTextureName("portia:chain").setCreativeTab(portiaItems);
        GameRegistry.registerItem(chain, "chain");
        diamondChain = new Item().setUnlocalizedName("diamondChain").setTextureName("portia:diamond_chain").setCreativeTab(portiaItems);
        GameRegistry.registerItem(diamondChain, "diamond_chain");
        ironNugget = new Item().setUnlocalizedName("ironNugget").setTextureName("portia:iron_nugget").setCreativeTab(portiaItems);
        GameRegistry.registerItem(ironNugget, "iron_nugget");
        diamondNugget = new Item().setUnlocalizedName("diamondNugget").setTextureName("portia:diamond_nugget").setCreativeTab(portiaItems);
        GameRegistry.registerItem(diamondNugget, "diamond_nugget");
        emeraldPickaxe = new ModPickaxe(emeraldItems).setUnlocalizedName("emeraldPickaxe").setTextureName("portia:emerald_pickaxe").setCreativeTab(portiaItems);
        GameRegistry.registerItem(emeraldPickaxe, "emerald_pickaxe");
        emeraldAxe = new ModAxe(emeraldItems).setUnlocalizedName("emeraldAxe").setTextureName("portia:emerald_axe").setCreativeTab(portiaItems);
        GameRegistry.registerItem(emeraldAxe, "emerald_axe");
        emeraldShovel = new ModSpade(emeraldItems).setUnlocalizedName("emeraldShovel").setTextureName("portia:emerald_shovel").setCreativeTab(portiaItems);
        GameRegistry.registerItem(emeraldShovel, "emerald_shovel");
        emeraldHoe = new ModHoe(emeraldItems).setUnlocalizedName("emeraldHoe").setTextureName("portia:emerald_hoe").setCreativeTab(portiaItems);
        GameRegistry.registerItem(emeraldHoe, "emerald_hoe");
        emeraldSword = new ModSword(emeraldItems).setUnlocalizedName("emeraldSword").setTextureName("portia:emerald_sword").setCreativeTab(portiaItems);
        GameRegistry.registerItem(emeraldSword, "emerald_sword");
        emeraldHelmet = new EmeraldArmor(emeraldArmor, 0, 0).setUnlocalizedName("emeraldHelmet").setTextureName("portia:emerald_helmet").setCreativeTab(portiaItems);
        GameRegistry.registerItem(emeraldHelmet, "emerald_helmet");
        emeraldChestplate = new EmeraldArmor(emeraldArmor, 0, 1).setUnlocalizedName("emeraldChestplate").setTextureName("portia:emerald_chestplate").setCreativeTab(portiaItems);
        GameRegistry.registerItem(emeraldChestplate, "emerald_chestplate");
        emeraldLeggings = new EmeraldArmor(emeraldArmor, 0, 2).setUnlocalizedName("emeraldLeggings").setTextureName("portia:emerald_leggings").setCreativeTab(portiaItems);
        GameRegistry.registerItem(emeraldLeggings, "emerald_leggings");
        emeraldBoots = new EmeraldArmor(emeraldArmor, 0, 3).setUnlocalizedName("emeraldBoots").setTextureName("portia:emerald_boots").setCreativeTab(portiaItems);
        GameRegistry.registerItem(emeraldBoots, "emerald_boots");
        redstonePickaxe = new ModPickaxe(redstoneItems).setUnlocalizedName("redstonePickaxe").setTextureName("portia:redstone_pickaxe").setCreativeTab(portiaItems);
        GameRegistry.registerItem(redstonePickaxe, "redstone_pickaxe");
        redstoneAxe = new ModAxe(redstoneItems).setUnlocalizedName("redstoneAxe").setTextureName("portia:redstone_axe").setCreativeTab(portiaItems);
        GameRegistry.registerItem(redstoneAxe, "redstone_axe");
        redstoneShovel = new ModSpade(redstoneItems).setUnlocalizedName("redstoneShovel").setTextureName("portia:redstone_shovel").setCreativeTab(portiaItems);
        GameRegistry.registerItem(redstoneShovel, "redstone_shovel");
        redstoneHoe = new ModHoe(redstoneItems).setUnlocalizedName("redstoneHoe").setTextureName("portia:redstone_hoe").setCreativeTab(portiaItems);
        GameRegistry.registerItem(redstoneHoe, "redstone_hoe");
        redstoneSword = new ModSword(redstoneItems).setUnlocalizedName("redstoneSword").setTextureName("portia:redstone_sword").setCreativeTab(portiaItems);
        GameRegistry.registerItem(redstoneSword, "redstone_sword");
        redstoneHelmet = new RedstoneArmor(redstoneArmor, 0, 0).setUnlocalizedName("redstoneHelmet").setTextureName("portia:redstone_helmet").setCreativeTab(portiaItems);
        GameRegistry.registerItem(redstoneHelmet, "redstone_helmet");
        redstoneChestplate = new RedstoneArmor(redstoneArmor, 0, 1).setUnlocalizedName("redstoneChestplate").setTextureName("portia:redstone_chestplate").setCreativeTab(portiaItems);
        GameRegistry.registerItem(redstoneChestplate, "redstone_chestplate");
        redstoneLeggings = new RedstoneArmor(redstoneArmor, 0, 2).setUnlocalizedName("redstoneLeggings").setTextureName("portia:redstone_leggings").setCreativeTab(portiaItems);
        GameRegistry.registerItem(redstoneLeggings, "redstone_leggings");
        redstoneBoots = new RedstoneArmor(redstoneArmor, 0, 3).setUnlocalizedName("redstoneBoots").setTextureName("portia:redstone_boots").setCreativeTab(portiaItems);
        GameRegistry.registerItem(redstoneBoots, "redstone_boots");
        lapisPickaxe = new ModPickaxe(lapisItems).setUnlocalizedName("lapisPickaxe").setTextureName("portia:lapis_pickaxe").setCreativeTab(portiaItems);
        GameRegistry.registerItem(lapisPickaxe, "lapis_pickaxe");
        lapisAxe = new ModAxe(lapisItems).setUnlocalizedName("lapisAxe").setTextureName("portia:lapis_axe").setCreativeTab(portiaItems);
        GameRegistry.registerItem(lapisAxe, "lapis_axe");
        lapisShovel = new ModSpade(lapisItems).setUnlocalizedName("lapisShovel").setTextureName("portia:lapis_shovel").setCreativeTab(portiaItems);
        GameRegistry.registerItem(lapisShovel, "lapis_shovel");
        lapisHoe = new ModHoe(lapisItems).setUnlocalizedName("lapisHoe").setTextureName("portia:lapis_hoe").setCreativeTab(portiaItems);
        GameRegistry.registerItem(lapisHoe, "lapis_hoe");
        lapisSword = new ModSword(lapisItems).setUnlocalizedName("lapisSword").setTextureName("portia:lapis_sword").setCreativeTab(portiaItems);
        GameRegistry.registerItem(lapisSword, "lapis_sword");
        lapisHelmet = new LapisArmor(lapisArmor, 0, 0).setUnlocalizedName("lapisHelmet").setTextureName("portia:lapis_helmet").setCreativeTab(portiaItems);
        GameRegistry.registerItem(lapisHelmet, "lapis_helmet");
        lapisChestplate = new LapisArmor(lapisArmor, 0, 1).setUnlocalizedName("lapisChestplate").setTextureName("portia:lapis_chestplate").setCreativeTab(portiaItems);
        GameRegistry.registerItem(lapisChestplate, "lapis_chestplate");
        lapisLeggings = new LapisArmor(lapisArmor, 0, 2).setUnlocalizedName("lapisLeggings").setTextureName("portia:lapis_leggings").setCreativeTab(portiaItems);
        GameRegistry.registerItem(lapisLeggings, "lapis_leggings");
        lapisBoots = new LapisArmor(lapisArmor, 0, 3).setUnlocalizedName("lapisBoots").setTextureName("portia:lapis_boots").setCreativeTab(portiaItems);
        GameRegistry.registerItem(lapisBoots, "lapis_boots");
        goldenDoorI = new ItemGoldenDoor(Material.iron).setUnlocalizedName("doorGolden").setTextureName("portia:golden_door").setCreativeTab(portiaBlocks);
        GameRegistry.registerItem(goldenDoorI, "golden_door_item");
        diamondDoorI = new ItemDiamondDoor(Material.iron).setUnlocalizedName("doorDiamond").setTextureName("portia:diamond_door").setCreativeTab(portiaBlocks);
        GameRegistry.registerItem(diamondDoorI, "diamond_door_item");
        emeraldDoorI = new ItemEmeraldDoor(Material.iron).setUnlocalizedName("doorEmerald").setTextureName("portia:emerald_door").setCreativeTab(portiaBlocks);
        GameRegistry.registerItem(emeraldDoorI, "emerald_door_item");
    }
    @EventHandler
    public void init(FMLInitializationEvent event) {
        GameRegistry.addRecipe(new ItemStack(Items.iron_horse_armor), new Object[]{"  I", "IWI", "III", 'I', Items.iron_ingot, 'W', Blocks.wool});
        GameRegistry.addRecipe(new ItemStack(Items.golden_horse_armor), new Object[]{"  I", "IWI", "III", 'I', Items.gold_ingot, 'W', Blocks.wool});
        GameRegistry.addRecipe(new ItemStack(Items.diamond_horse_armor), new Object[]{"  I", "IWI", "III", 'I', Items.diamond, 'W', Blocks.wool});
        GameRegistry.addRecipe(new ItemStack(Items.saddle), new Object[]{"LLL", "LIL", "I I", 'L', Items.leather, 'I', Items.iron_ingot});
        GameRegistry.addRecipe(new ItemStack(Items.chainmail_helmet), new Object[]{"NNN", "N N", 'N', chain});
        GameRegistry.addRecipe(new ItemStack(Items.chainmail_chestplate), new Object[]{"N N", "NNN", "NNN", 'N', chain});
        GameRegistry.addRecipe(new ItemStack(Items.chainmail_leggings), new Object[]{"NNN", "N N", "N N", 'N', chain});
        GameRegistry.addRecipe(new ItemStack(Items.chainmail_boots), new Object[]{"N N", "N N", 'N', chain});

        GameRegistry.addRecipe(new ItemStack(chain), new Object[]{"C", "C", "C", 'C', ironNugget});
        GameRegistry.addRecipe(new ItemStack(ironNugget, 9), new Object[]{"I", 'I', Items.iron_ingot});
        GameRegistry.addRecipe(new ItemStack(emeraldPickaxe), new Object[]{"EEE", " S ", " S ", 'E', Items.emerald, 'S', Items.stick});
        GameRegistry.addRecipe(new ItemStack(emeraldAxe), new Object[]{"EE", "ES", " S", 'E', Items.emerald, 'S', Items.stick});
        GameRegistry.addRecipe(new ItemStack(emeraldShovel), new Object[]{"E", "S", "S", 'E', Items.emerald, 'S', Items.stick});
        GameRegistry.addRecipe(new ItemStack(emeraldHoe), new Object[]{"EE", " S", " S", 'E', Items.emerald, 'S', Items.stick});
        GameRegistry.addRecipe(new ItemStack(emeraldSword), new Object[]{"E", "E", "S", 'E', Items.emerald, 'S', Items.stick});
        GameRegistry.addRecipe(new ItemStack(emeraldHelmet), new Object[]{"EEE", "E E", 'E', Items.emerald});
        GameRegistry.addRecipe(new ItemStack(emeraldChestplate), new Object[]{"E E", "EEE", "EEE", 'E', Items.emerald});
        GameRegistry.addRecipe(new ItemStack(emeraldLeggings), new Object[]{"EEE", "E E", "E E", 'E', Items.emerald});
        GameRegistry.addRecipe(new ItemStack(emeraldBoots), new Object[]{"E E", "E E", 'E', Items.emerald});
        GameRegistry.addRecipe(new ItemStack(redstonePickaxe), new Object[]{"RRR", " S ", " S ", 'R', Items.redstone, 'S', Items.stick});
        GameRegistry.addRecipe(new ItemStack(redstoneAxe), new Object[]{"RR", "RS", " S", 'R', Items.redstone, 'S', Items.stick});
        GameRegistry.addRecipe(new ItemStack(redstoneShovel), new Object[]{"R", "S", "S", 'R', Items.redstone, 'S', Items.stick});
        GameRegistry.addRecipe(new ItemStack(redstoneHoe), new Object[]{"RR", " S", " S", 'R', Items.redstone, 'S', Items.stick});
        GameRegistry.addRecipe(new ItemStack(redstoneSword), new Object[]{"R", "R", "S", 'R', Items.redstone, 'S', Items.stick});
        GameRegistry.addRecipe(new ItemStack(redstoneHelmet), new Object[]{"RRR", "R R", 'R', Items.redstone});
        GameRegistry.addRecipe(new ItemStack(redstoneChestplate), new Object[]{"R R", "RRR", "RRR", 'R', Items.redstone});
        GameRegistry.addRecipe(new ItemStack(redstoneLeggings), new Object[]{"RRR", "R R", "R R", 'R', Items.redstone});
        GameRegistry.addRecipe(new ItemStack(redstoneBoots), new Object[]{"R R", "R R", 'R', Items.redstone});
        GameRegistry.addRecipe(new ItemStack(lapisPickaxe), new Object[]{"LLL", " S ", " S ", 'L', new ItemStack(Items.dye, 1, 4), 'S', Items.stick});
        GameRegistry.addRecipe(new ItemStack(lapisAxe), new Object[]{"RR", "RS", " S", 'R', new ItemStack(Items.dye, 1, 4), 'S', Items.stick});
        GameRegistry.addRecipe(new ItemStack(lapisShovel), new Object[]{"L", "S", "S", 'L', new ItemStack(Items.dye, 1, 4), 'S', Items.stick});
        GameRegistry.addRecipe(new ItemStack(lapisHoe), new Object[]{"LL", " S", " S", 'L', new ItemStack(Items.dye, 1, 4), 'S', Items.stick});
        GameRegistry.addRecipe(new ItemStack(lapisSword), new Object[]{"L", "L", "S", 'L', new ItemStack(Items.dye, 1, 4), 'S', Items.stick});
        GameRegistry.addRecipe(new ItemStack(lapisHelmet), new Object[]{"LLL", "L L", 'L', new ItemStack(Items.dye, 1, 4)});
        GameRegistry.addRecipe(new ItemStack(lapisChestplate), new Object[]{"L L", "LLL", "LLL", 'L', new ItemStack(Items.dye, 1, 4)});
        GameRegistry.addRecipe(new ItemStack(lapisLeggings), new Object[]{"LLL", "L L", "L L", 'L', new ItemStack(Items.dye, 1, 4)});
        GameRegistry.addRecipe(new ItemStack(lapisBoots), new Object[]{"L L", "L L", 'L', new ItemStack(Items.dye, 1, 4)});
        GameRegistry.addRecipe(new ItemStack(goldenDoorI), new Object[]{"GG", "GG", "GG", 'G', Items.gold_ingot});
        GameRegistry.addRecipe(new ItemStack(diamondDoorI), new Object[]{"DD", "DD", "DD", 'D', Items.diamond});
        GameRegistry.addRecipe(new ItemStack(emeraldDoorI), new Object[]{"EE", "EE", "EE", 'E', Items.emerald});

        GameRegistry.addRecipe(new ItemStack(oldCloth, 1, 0), new Object[]{"W", 'W', new ItemStack(Blocks.wool, 1, 0)});
        GameRegistry.addRecipe(new ItemStack(oldCloth, 1, 1), new Object[]{"W", 'W', new ItemStack(Blocks.wool, 1, 1)});
        GameRegistry.addRecipe(new ItemStack(oldCloth, 1, 2), new Object[]{"W", 'W', new ItemStack(Blocks.wool, 1, 2)});
        GameRegistry.addRecipe(new ItemStack(oldCloth, 1, 3), new Object[]{"W", 'W', new ItemStack(Blocks.wool, 1, 3)});
        GameRegistry.addRecipe(new ItemStack(oldCloth, 1, 4), new Object[]{"W", 'W', new ItemStack(Blocks.wool, 1, 4)});
        GameRegistry.addRecipe(new ItemStack(oldCloth, 1, 5), new Object[]{"W", 'W', new ItemStack(Blocks.wool, 1, 5)});
        GameRegistry.addRecipe(new ItemStack(oldCloth, 1, 6), new Object[]{"W", 'W', new ItemStack(Blocks.wool, 1, 6)});
        GameRegistry.addRecipe(new ItemStack(oldCloth, 1, 7), new Object[]{"W", 'W', new ItemStack(Blocks.wool, 1, 7)});
        GameRegistry.addRecipe(new ItemStack(oldCloth, 1, 8), new Object[]{"W", 'W', new ItemStack(Blocks.wool, 1, 8)});
        GameRegistry.addRecipe(new ItemStack(oldCloth, 1, 9), new Object[]{"W", 'W', new ItemStack(Blocks.wool, 1, 9)});
        GameRegistry.addRecipe(new ItemStack(oldCloth, 1, 10), new Object[]{"W", 'W', new ItemStack(Blocks.wool, 1, 10)});
        GameRegistry.addRecipe(new ItemStack(oldCloth, 1, 11), new Object[]{"W", 'W', new ItemStack(Blocks.wool, 1, 11)});
        GameRegistry.addRecipe(new ItemStack(oldCloth, 1, 12), new Object[]{"W", 'W', new ItemStack(Blocks.wool, 1, 12)});
        GameRegistry.addRecipe(new ItemStack(oldCloth, 1, 13), new Object[]{"W", 'W', new ItemStack(Blocks.wool, 1, 13)});
        GameRegistry.addRecipe(new ItemStack(oldCloth, 1, 14), new Object[]{"W", 'W', new ItemStack(Blocks.wool, 1, 14)});
        GameRegistry.addRecipe(new ItemStack(oldCloth, 1, 15), new Object[]{"W", 'W', new ItemStack(Blocks.wool, 1, 15)});
        GameRegistry.addRecipe(new ItemStack(Blocks.wool, 1, 0), new Object[]{"W", 'W', new ItemStack(oldCloth, 1, 0)});
        GameRegistry.addRecipe(new ItemStack(Blocks.wool, 1, 1), new Object[]{"W", 'W', new ItemStack(oldCloth, 1, 1)});
        GameRegistry.addRecipe(new ItemStack(Blocks.wool, 1, 2), new Object[]{"W", 'W', new ItemStack(oldCloth, 1, 2)});
        GameRegistry.addRecipe(new ItemStack(Blocks.wool, 1, 3), new Object[]{"W", 'W', new ItemStack(oldCloth, 1, 3)});
        GameRegistry.addRecipe(new ItemStack(Blocks.wool, 1, 4), new Object[]{"W", 'W', new ItemStack(oldCloth, 1, 4)});
        GameRegistry.addRecipe(new ItemStack(Blocks.wool, 1, 5), new Object[]{"W", 'W', new ItemStack(oldCloth, 1, 5)});
        GameRegistry.addRecipe(new ItemStack(Blocks.wool, 1, 6), new Object[]{"W", 'W', new ItemStack(oldCloth, 1, 6)});
        GameRegistry.addRecipe(new ItemStack(Blocks.wool, 1, 7), new Object[]{"W", 'W', new ItemStack(oldCloth, 1, 7)});
        GameRegistry.addRecipe(new ItemStack(Blocks.wool, 1, 8), new Object[]{"W", 'W', new ItemStack(oldCloth, 1, 8)});
        GameRegistry.addRecipe(new ItemStack(Blocks.wool, 1, 9), new Object[]{"W", 'W', new ItemStack(oldCloth, 1, 9)});
        GameRegistry.addRecipe(new ItemStack(Blocks.wool, 1, 10), new Object[]{"W", 'W', new ItemStack(oldCloth, 1, 10)});
        GameRegistry.addRecipe(new ItemStack(Blocks.wool, 1, 11), new Object[]{"W", 'W', new ItemStack(oldCloth, 1, 11)});
        GameRegistry.addRecipe(new ItemStack(Blocks.wool, 1, 12), new Object[]{"W", 'W', new ItemStack(oldCloth, 1, 12)});
        GameRegistry.addRecipe(new ItemStack(Blocks.wool, 1, 13), new Object[]{"W", 'W', new ItemStack(oldCloth, 1, 13)});
        GameRegistry.addRecipe(new ItemStack(Blocks.wool, 1, 14), new Object[]{"W", 'W', new ItemStack(oldCloth, 1, 14)});
        GameRegistry.addRecipe(new ItemStack(Blocks.wool, 1, 15), new Object[]{"W", 'W', new ItemStack(oldCloth, 1, 15)});
        GameRegistry.addRecipe(new ItemStack(coloredWood, 1, 0), new Object[]{" D ", "DSD", " D ", 'D', new ItemStack(Items.dye, 1, 15), 'S', new ItemStack(Blocks.planks)});
        GameRegistry.addRecipe(new ItemStack(coloredWood, 1, 1), new Object[]{" D ", "DSD", " D ", 'D', new ItemStack(Items.dye, 1, 14), 'S', new ItemStack(Blocks.planks)});
        GameRegistry.addRecipe(new ItemStack(coloredWood, 1, 2), new Object[]{" D ", "DSD", " D ", 'D', new ItemStack(Items.dye, 1, 13), 'S', new ItemStack(Blocks.planks)});
        GameRegistry.addRecipe(new ItemStack(coloredWood, 1, 3), new Object[]{" D ", "DSD", " D ", 'D', new ItemStack(Items.dye, 1, 12), 'S', new ItemStack(Blocks.planks)});
        GameRegistry.addRecipe(new ItemStack(coloredWood, 1, 4), new Object[]{" D ", "DSD", " D ", 'D', new ItemStack(Items.dye, 1, 11), 'S', new ItemStack(Blocks.planks)});
        GameRegistry.addRecipe(new ItemStack(coloredWood, 1, 5), new Object[]{" D ", "DSD", " D ", 'D', new ItemStack(Items.dye, 1, 10), 'S', new ItemStack(Blocks.planks)});
        GameRegistry.addRecipe(new ItemStack(coloredWood, 1, 6), new Object[]{" D ", "DSD", " D ", 'D', new ItemStack(Items.dye, 1, 9), 'S', new ItemStack(Blocks.planks)});
        GameRegistry.addRecipe(new ItemStack(coloredWood, 1, 7), new Object[]{" D ", "DSD", " D ", 'D', new ItemStack(Items.dye, 1, 8), 'S', new ItemStack(Blocks.planks)});
        GameRegistry.addRecipe(new ItemStack(coloredWood, 1, 8), new Object[]{" D ", "DSD", " D ", 'D', new ItemStack(Items.dye, 1, 7), 'S', new ItemStack(Blocks.planks)});
        GameRegistry.addRecipe(new ItemStack(coloredWood, 1, 9), new Object[]{" D ", "DSD", " D ", 'D', new ItemStack(Items.dye, 1, 6), 'S', new ItemStack(Blocks.planks)});
        GameRegistry.addRecipe(new ItemStack(coloredWood, 1, 10), new Object[]{" D ", "DSD", " D ", 'D', new ItemStack(Items.dye, 1, 5), 'S', new ItemStack(Blocks.planks)});
        GameRegistry.addRecipe(new ItemStack(coloredWood, 1, 11), new Object[]{" D ", "DSD", " D ", 'D', new ItemStack(Items.dye, 1, 4), 'S', new ItemStack(Blocks.planks)});
        GameRegistry.addRecipe(new ItemStack(coloredWood, 1, 12), new Object[]{" D ", "DSD", " D ", 'D', new ItemStack(Items.dye, 1, 3), 'S', new ItemStack(Blocks.planks)});
        GameRegistry.addRecipe(new ItemStack(coloredWood, 1, 13), new Object[]{" D ", "DSD", " D ", 'D', new ItemStack(Items.dye, 1, 2), 'S', new ItemStack(Blocks.planks)});
        GameRegistry.addRecipe(new ItemStack(coloredWood, 1, 14), new Object[]{" D ", "DSD", " D ", 'D', new ItemStack(Items.dye, 1, 1), 'S', new ItemStack(Blocks.planks)});
        GameRegistry.addRecipe(new ItemStack(coloredWood, 1, 15), new Object[]{" D ", "DSD", " D ", 'D', new ItemStack(Items.dye, 1, 0), 'S', new ItemStack(Blocks.planks)});
        GameRegistry.addRecipe(new ItemStack(coloredCobble, 1, 0), new Object[]{" D ", "DSD", " D ", 'D', new ItemStack(Items.dye, 1, 15), 'S', new ItemStack(Blocks.cobblestone)});
        GameRegistry.addRecipe(new ItemStack(coloredCobble, 1, 1), new Object[]{" D ", "DSD", " D ", 'D', new ItemStack(Items.dye, 1, 14), 'S', new ItemStack(Blocks.cobblestone)});
        GameRegistry.addRecipe(new ItemStack(coloredCobble, 1, 2), new Object[]{" D ", "DSD", " D ", 'D', new ItemStack(Items.dye, 1, 13), 'S', new ItemStack(Blocks.cobblestone)});
        GameRegistry.addRecipe(new ItemStack(coloredCobble, 1, 3), new Object[]{" D ", "DSD", " D ", 'D', new ItemStack(Items.dye, 1, 12), 'S', new ItemStack(Blocks.cobblestone)});
        GameRegistry.addRecipe(new ItemStack(coloredCobble, 1, 4), new Object[]{" D ", "DSD", " D ", 'D', new ItemStack(Items.dye, 1, 11), 'S', new ItemStack(Blocks.cobblestone)});
        GameRegistry.addRecipe(new ItemStack(coloredCobble, 1, 5), new Object[]{" D ", "DSD", " D ", 'D', new ItemStack(Items.dye, 1, 10), 'S', new ItemStack(Blocks.cobblestone)});
        GameRegistry.addRecipe(new ItemStack(coloredCobble, 1, 6), new Object[]{" D ", "DSD", " D ", 'D', new ItemStack(Items.dye, 1, 9), 'S', new ItemStack(Blocks.cobblestone)});
        GameRegistry.addRecipe(new ItemStack(coloredCobble, 1, 7), new Object[]{" D ", "DSD", " D ", 'D', new ItemStack(Items.dye, 1, 8), 'S', new ItemStack(Blocks.cobblestone)});
        GameRegistry.addRecipe(new ItemStack(coloredCobble, 1, 8), new Object[]{" D ", "DSD", " D ", 'D', new ItemStack(Items.dye, 1, 7), 'S', new ItemStack(Blocks.cobblestone)});
        GameRegistry.addRecipe(new ItemStack(coloredCobble, 1, 9), new Object[]{" D ", "DSD", " D ", 'D', new ItemStack(Items.dye, 1, 6), 'S', new ItemStack(Blocks.cobblestone)});
        GameRegistry.addRecipe(new ItemStack(coloredCobble, 1, 10), new Object[]{" D ", "DSD", " D ", 'D', new ItemStack(Items.dye, 1, 5), 'S', new ItemStack(Blocks.cobblestone)});
        GameRegistry.addRecipe(new ItemStack(coloredCobble, 1, 11), new Object[]{" D ", "DSD", " D ", 'D', new ItemStack(Items.dye, 1, 4), 'S', new ItemStack(Blocks.cobblestone)});
        GameRegistry.addRecipe(new ItemStack(coloredCobble, 1, 12), new Object[]{" D ", "DSD", " D ", 'D', new ItemStack(Items.dye, 1, 3), 'S', new ItemStack(Blocks.cobblestone)});
        GameRegistry.addRecipe(new ItemStack(coloredCobble, 1, 13), new Object[]{" D ", "DSD", " D ", 'D', new ItemStack(Items.dye, 1, 2), 'S', new ItemStack(Blocks.cobblestone)});
        GameRegistry.addRecipe(new ItemStack(coloredCobble, 1, 14), new Object[]{" D ", "DSD", " D ", 'D', new ItemStack(Items.dye, 1, 1), 'S', new ItemStack(Blocks.cobblestone)});
        GameRegistry.addRecipe(new ItemStack(coloredCobble, 1, 15), new Object[]{" D ", "DSD", " D ", 'D', new ItemStack(Items.dye, 1, 0), 'S', new ItemStack(Blocks.cobblestone)});
        GameRegistry.addRecipe(new ItemStack(coloredStone, 1, 0), new Object[]{" D ", "DSD", " D ", 'D', new ItemStack(Items.dye, 1, 15), 'S', new ItemStack(Blocks.stone)});
        GameRegistry.addRecipe(new ItemStack(coloredStone, 1, 1), new Object[]{" D ", "DSD", " D ", 'D', new ItemStack(Items.dye, 1, 14), 'S', new ItemStack(Blocks.stone)});
        GameRegistry.addRecipe(new ItemStack(coloredStone, 1, 2), new Object[]{" D ", "DSD", " D ", 'D', new ItemStack(Items.dye, 1, 13), 'S', new ItemStack(Blocks.stone)});
        GameRegistry.addRecipe(new ItemStack(coloredStone, 1, 3), new Object[]{" D ", "DSD", " D ", 'D', new ItemStack(Items.dye, 1, 12), 'S', new ItemStack(Blocks.stone)});
        GameRegistry.addRecipe(new ItemStack(coloredStone, 1, 4), new Object[]{" D ", "DSD", " D ", 'D', new ItemStack(Items.dye, 1, 11), 'S', new ItemStack(Blocks.stone)});
        GameRegistry.addRecipe(new ItemStack(coloredStone, 1, 5), new Object[]{" D ", "DSD", " D ", 'D', new ItemStack(Items.dye, 1, 10), 'S', new ItemStack(Blocks.stone)});
        GameRegistry.addRecipe(new ItemStack(coloredStone, 1, 6), new Object[]{" D ", "DSD", " D ", 'D', new ItemStack(Items.dye, 1, 9), 'S', new ItemStack(Blocks.stone)});
        GameRegistry.addRecipe(new ItemStack(coloredStone, 1, 7), new Object[]{" D ", "DSD", " D ", 'D', new ItemStack(Items.dye, 1, 8), 'S', new ItemStack(Blocks.stone)});
        GameRegistry.addRecipe(new ItemStack(coloredStone, 1, 8), new Object[]{" D ", "DSD", " D ", 'D', new ItemStack(Items.dye, 1, 7), 'S', new ItemStack(Blocks.stone)});
        GameRegistry.addRecipe(new ItemStack(coloredStone, 1, 9), new Object[]{" D ", "DSD", " D ", 'D', new ItemStack(Items.dye, 1, 6), 'S', new ItemStack(Blocks.stone)});
        GameRegistry.addRecipe(new ItemStack(coloredStone, 1, 10), new Object[]{" D ", "DSD", " D ", 'D', new ItemStack(Items.dye, 1, 5), 'S', new ItemStack(Blocks.stone)});
        GameRegistry.addRecipe(new ItemStack(coloredStone, 1, 11), new Object[]{" D ", "DSD", " D ", 'D', new ItemStack(Items.dye, 1, 4), 'S', new ItemStack(Blocks.stone)});
        GameRegistry.addRecipe(new ItemStack(coloredStone, 1, 12), new Object[]{" D ", "DSD", " D ", 'D', new ItemStack(Items.dye, 1, 3), 'S', new ItemStack(Blocks.stone)});
        GameRegistry.addRecipe(new ItemStack(coloredStone, 1, 13), new Object[]{" D ", "DSD", " D ", 'D', new ItemStack(Items.dye, 1, 2), 'S', new ItemStack(Blocks.stone)});
        GameRegistry.addRecipe(new ItemStack(coloredStone, 1, 14), new Object[]{" D ", "DSD", " D ", 'D', new ItemStack(Items.dye, 1, 1), 'S', new ItemStack(Blocks.stone)});
        GameRegistry.addRecipe(new ItemStack(coloredStone, 1, 15), new Object[]{" D ", "DSD", " D ", 'D', new ItemStack(Items.dye, 1, 0), 'S', new ItemStack(Blocks.stone)});

    }
    @EventHandler
    public void postInit(FMLPostInitializationEvent event) {

    }
    public static CreativeTabs portiaBlocks = new CreativeTabs("portiaBlocks") {
        @Override
        public Item getTabIconItem() {
            return new ItemStack(oldCloth).getItem();
        }
    };
    public static CreativeTabs portiaItems = new CreativeTabs("portiaItems") {
        @Override
        public Item getTabIconItem() {
            return new ItemStack(chain).getItem();
        }
    };

}
